### ISSUE TITLE
What is a good choice for vocab.txt ?

### ISSUE THREAD

**Issue by tim5go** [allenai/document-qa#20]
For the script `run_on_user_documents.py`, it takes input paragraphs and user question as vocabulary set to build the tensorflow graph.

But in real application, we want the graph is built in advance.
What is a good choice for vocab.txt in general when we set the following:
`model.set_input_spec(ParagraphAndQuestionSpec(batch_size=len(context)), voc)`?

I tried the whole vocabulary set for `glove.840B.300d.txt` as input.
But it seems so large that causing the following problem:
`ValueError: Cannot create a tensor proto whose content is larger than 2GB.`

**Comment by chrisc36** [comment]
I think it would be possible to use all of Glove, but you might have to modify some code so that the embedding matrix is held as a Variable instead of a constant. 

Otherwise the obvious thing to do is to use a list of the "n" most common words in some representative corpus. For our demo, we used all words that occurred more then 10 times in the TriviaQA evidence corpus, and that seems to work fine.
