### ISSUE TITLE
EM scores are higher than F1 scores

### ISSUE THREAD

**Issue by felixgwu** [allenai/document-qa#8]
After training the model on TriviaQA Web, I observed that the exact match scores are higher than the F1 scores on both training and test sets.
To my knowledge, the F1 score is always greater than or equal to the exact score.
I wonder if the labels are swapped.
Here is the command I used:
```
python docqa/scripts/ablate_triviaqa.py -n 8 shared-norm-600 save/web-shared-norm-600
```

![image](https://user-images.githubusercontent.com/7753366/32792050-674325d4-c930-11e7-9197-d4cdaee1b2bb.png)

![image](https://user-images.githubusercontent.com/7753366/32791950-2cd97902-c930-11e7-8fdf-0bc85bac863e.png)

BTW, could you explain the difference between **paragraph-text-em**, **question-text-em**, and **text-em-k-tau**?
Thanks!

**Comment by chrisc36** [comment]
You are correct em/f1 should be switched, thanks for pointing that out. I somehow imported the evaluation metrics with the wrong names.

I added a fix, I also added a comment explaining the output, which I will paste here for completeness:

Evaluation is a bit tricky in this case, since we are generally sampling paragraphs each epoch we can't report exact numbers as your would see when running the evaluation scripts. Instead we report some numbers aimed to get an approximate idea of what is going on:

1. question-text-{em|f1}, accuracy on questions-document pairs (or just questions if `per_doc=False`) using all sampled paragraphs when taking the model's highest confidence answer
2. paragraph-text-{em|f1}, accuracy on answer-containing paragraphs (if `paragraph_level=True`)
3. The Kendel Tau relation between the model's confidence and the paragraph's f1/em score,
       (if `k_tau=True`) intended to measure how valid the model's confidence score is
       when it comes to ranking.

**Comment by felixgwu** [comment]
Thanks a lot!

**Comment by chrisc36** [comment]
No problem. Just to check, were you able to reproduce our dev scores on TriviaQA web? I think you are the first user trying to re-train the model.

**Comment by felixgwu** [comment]
It seems to take days to train. It's at epoch 6 now. It achieves ~0.75 F1 score and is still increasing, which is already much better than all previous published models!
I wonder if the code allows me to use multiple GPUs. 

Also, I noticed that there is a `continue.py` script. Is it used for continuing training the model if the job dies somehow in the middle?

**Comment by chrisc36** [comment]
Yes, "continue.py" can resume training if the run crashes. However it will "lose its place" within the training data, so training will be restarted from a fresh epoch.

We don't support multiple GPUs at the moment.

Note the the scores on tensorboard are likely to be optimistic since they are computed using a (biased) sample of paragraphs for each question. Although if you get > 71.0 F1 using the "triviaqa_full_document_eval.py" script let me know, our final model reached just under 71.0 F1.

**Comment by felixgwu** [comment]
I got the following error when running "triviaqa_full_document_eval.py"

This is how I ran the script:
```sh
file=web-shared-norm-600-1115-151714
python docqa/eval/triviaqa_full_document_eval.py --n_processes 8 -c web-dev --tokens 600 -f tfidf -b 32 -o preds/${file}-question-output.json -p preds/${file}-paragraph-output.csv save/$file
```
It's different from the one in README.md since I assume that I should use `--tokens 600` when running with a shared-norm-600 model. Also, I got an error when using `-f tfidf-15`, it told me that "tfidf-15" is not a valid option for "-f". Hopefully, this is correct.

Here is the error message:
```
Restoring variables
Restoring EMA variables
Begin evaluation
web-dev: 100%|████████████████████████████| 10397/10397 [47:15<00:00,  9.33it/s]
scoring: 100%|████████████████████████| 332692/332692 [03:12<00:00, 1725.20it/s]
Saving question result
Loading proper filenames
Traceback (most recent call last):
  File "docqa/eval/triviaqa_full_document_eval.py", line 296, in <module>
    main()
  File "docqa/eval/triviaqa_full_document_eval.py", line 274, in main
    f1 = compute_model_scores(df, "predicted_score", "text_f1", group_by)
  File "/home/fw245/clones/document-qa/docqa/eval/ranked_triviaqa_scores.py", line 20, in compute_model_scores
    used_predictions = group[max_over].expanding().apply(lambda x: x.argmax())
  File "/usr/local/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 2360, in __getattr__
    (type(self).__name__, name))
AttributeError: 'Series' object has no attribute 'expanding'
```

Even though the job failed, I got the json output `web-shared-norm-600-1115-151714-question-output.json`. I assume this is a correct prediction.
I evaluated this prediction file with the official evaluation script of TriviaQA and got these numbers:
EM: 65.829702 F1: 70.956870

**Comment by chrisc36** [comment]
Well, the official results are close to what I got: 66.04 EM and 70.98 F1. Thats good to know. Note I used a paragraph size of 800 during testing, it might make a small difference. 

I think the error is due to using an older version of pandas, I will update the requirements file to require a more recent version.
